[advisories]
version = 2
yanked = "deny"
unmaintained = "workspace"

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
