[package]
name = "oxgraph-python"
version = "0.0.0"
description = "Python bindings for OxGraph."
publish = false
authors = ["oxgraph contributors"]
edition = "2024"
repository = "https://github.com/oxgraph/oxgraph"
license = "MIT"

[workspace]

[lib]
name = "_oxgraph"
crate-type = ["cdylib", "rlib"]

[dependencies]
oxgraph-algo = { version = "0.4.1", path = "../../crates/oxgraph-algo", features = ["std"] }
oxgraph-csr = { version = "0.4.1", path = "../../crates/oxgraph-csr", features = ["build"] }
oxgraph-graph = { version = "0.4.1", path = "../../crates/oxgraph-graph" }
oxgraph-hyper = { version = "0.4.1", path = "../../crates/oxgraph-hyper" }
oxgraph-hyper-bcsr = { version = "0.4.1", path = "../../crates/oxgraph-hyper-bcsr", features = [
  "build",
] }
oxgraph-snapshot = { version = "0.4.1", path = "../../crates/oxgraph-snapshot" }
oxgraph-topology = { version = "0.4.1", path = "../../crates/oxgraph-topology" }
pyo3 = { version = "0.28.3", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.28.3"

[lints.rust]
rust_2024_compatibility = { level = "deny", priority = -1 }
missing_docs = "deny"
unreachable_pub = "deny"
unsafe_code = "allow"
unexpected_cfgs = { level = "deny", check-cfg = ["cfg(kani)"] }

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cognitive_complexity = "deny"
excessive_nesting = "deny"
too_many_arguments = "deny"
too_many_lines = "deny"
type_complexity = "deny"
missing_docs_in_private_items = "deny"
expect_used = "deny"
unwrap_used = "deny"
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
multiple_crate_versions = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }
