[package]
name = "oxgraph-topology"
version.workspace = true
license.workspace = true
description = "Storage-agnostic core traits for discrete topology views."
categories.workspace = true
keywords.workspace = true
readme = "README.md"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
