[package]
name = "oxgraph-hyper"
version.workspace = true
license.workspace = true
description = "Storage-agnostic core traits for hypergraph views."
categories.workspace = true
keywords.workspace = true
readme.workspace = true

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
oxgraph-topology = { version = "0.1.0", path = "../oxgraph-topology" }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
