[package]
name = "oxgraph-snapshot"
version.workspace = true
license.workspace = true
description = "Topology-agnostic byte-level snapshot container."
categories.workspace = true
keywords.workspace = true
readme.workspace = true

authors.workspace = true
edition.workspace = true
repository.workspace = true

[features]
default = []
alloc = ["oxgraph-layout-util/alloc"]
std = ["alloc"]

[dependencies]
oxgraph-layout-util = { version = "0.4.0", path = "../oxgraph-layout-util", default-features = false }
zerocopy = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }

[[bench]]
name = "container"
harness = false

[lints]
workspace = true
